Add files via upload

diff --git a/moodle/.travis.yml b/moodle/.travis.yml
--- a/moodle/.travis.yml
+++ b/moodle/.travis.yml
@@ -16,8 +16,30 @@ services:
     - mysql
     - docker
 
+php:
+    # We only run the highest and lowest supported versions to reduce the load on travis-ci.org.
+    - 7.4
+    - 7.2
+
 addons:
   postgresql: "9.6"
+
+env:
+    # Although we want to run these jobs and see failures as quickly as possible, we also want to get the slowest job to
+    # start first so that the total run time is not too high.
+    #
+    # We only run MySQL on PHP 7.2, so run that first.
+    # CI Tests should be second-highest in priority as these only take <= 60 seconds to run under normal circumstances.
+    # Postgres is significantly is pretty reasonable in its run-time.
+
+    # Run CI Tests without running PHPUnit.
+    - DB=none     TASK=CITEST
+
+    # Run unit tests on Postgres
+    - DB=pgsql    TASK=PHPUNIT
+
+    # Perform an upgrade test too.
+    - DB=pgsql    TASK=UPGRADE
 
 jobs:
     # Enable fast finish.
@@ -26,35 +48,12 @@ jobs:
     fast_finish: true
 
     include:
-        # First all the lowest php ones (7.3)
-        - php: 7.3
-          env: DB=none     TASK=CITEST
-        - php: 7.3
-          env: DB=none     TASK=GRUNT    NVM_VERSION='lts/carbon'
-
-        - if: env(MOODLE_DATABASE) = "pgsql" OR env(MOODLE_DATABASE) = "all" OR env(MOODLE_DATABASE) IS NOT present
-          php: 7.3
-          env: DB=pgsql    TASK=PHPUNIT
-
-        - if: env(MOODLE_DATABASE) = "mysqli" OR env(MOODLE_DATABASE) = "all"
-          php: 7.3
+          # Run mysql only on highest - it's just too slow
+        - php: 7.4
           env: DB=mysqli   TASK=PHPUNIT
-
-        # Then, conditionally, all the highest php ones (7.4)
-        - if: env(MOODLE_PHP) = "all"
-          php: 7.4
-          env: DB=none     TASK=CITEST
-        - if: env(MOODLE_PHP) = "all"
-          php: 7.4
-          env: DB=none     TASK=GRUNT    NVM_VERSION='lts/carbon'
-
-        - if: env(MOODLE_PHP) = "all" AND (env(MOODLE_DATABASE) = "pgsql" OR env(MOODLE_DATABASE) = "all" OR env(MOODLE_DATABASE) IS NOT present)
-          php: 7.4
-          env: DB=pgsql    TASK=PHPUNIT
-
-        - if: env(MOODLE_PHP) = "all" AND (env(MOODLE_DATABASE) = "mysqli" OR env(MOODLE_DATABASE) = "all")
-          php: 7.4
-          env: DB=mysqli   TASK=PHPUNIT
+          # Run grunt/npm install on highest version too ('node' is an alias for the latest node.js version.)
+        - php: 7.4
+          env: DB=none     TASK=GRUNT   NVM_VERSION='lts/carbon'
 
 cache:
     directories:
@@ -94,46 +93,56 @@ install:
                 composer config github-oauth.github.com $GITHUB_APITOKEN;
                 echo 'auth.json' >> .git/info/exclude
             fi
+
             echo 'extension="redis.so"' > /tmp/redis.ini
             phpenv config-add /tmp/redis.ini
+
             # Install composer dependencies.
             # We need --no-interaction in case we hit API limits for composer. This causes it to fall back to a standard clone.
             # Typically it should be able to use the Composer cache if any other job has already completed before we started here.
             travis_retry composer install --prefer-dist --no-interaction;
         fi
+
     - >
         if [ "$TASK" = 'GRUNT' ];
         then
             nvm install $NVM_VERSION ;
             nvm use $NVM_VERSION ;
         fi
+
 before_script:
     - phpenv config-rm xdebug.ini
     - >
-      if [ "$TASK" = 'PHPUNIT' ];
+      if [ "$TASK" = 'PHPUNIT' -o "$TASK" = 'UPGRADE' ];
       then
         # Copy generic configuration in place.
         cp config-dist.php config.php ;
+
         # Create the moodledata directory.
         mkdir -p "$HOME"/roots/base
+
         # The database name and password.
         sed -i \
           -e "s%= 'moodle'%= 'travis_ci_test'%" \
           -e "s%= 'password'%= ''%" \
           config.php ;
+
         # The wwwroot and dataroot.
         sed -i \
           -e "s%http://example.com/moodle%https://localhost%" \
           -e "s%/home/example/moodledata%/home/travis/roots/base%" \
           config.php ;
+
         if [ "$DB" = 'pgsql' ];
         then
           # Postgres-specific setup.
           sed -i \
             -e "s%= 'username'%= 'postgres'%" \
             config.php ;
+
           psql -c 'CREATE DATABASE travis_ci_test;' -U postgres;
         fi
+
         if [ "$DB" = 'mysqli' ];
         then
           # MySQL-specific setup.
@@ -142,17 +151,20 @@ before_script:
             -e "s%= 'username'%= 'travis'%" \
             -e "s%=> 'utf8mb4_unicode_ci'%=> 'utf8mb4_bin'%" \
             config.php;
+
           mysql -u root -e 'SET GLOBAL innodb_file_format=barracuda;' ;
           mysql -u root -e 'SET GLOBAL innodb_file_per_table=ON;' ;
           mysql -u root -e 'SET GLOBAL innodb_large_prefix=ON;' ;
           mysql -e 'CREATE DATABASE travis_ci_test DEFAULT CHARACTER SET utf8mb4 DEFAULT COLLATE utf8mb4_bin;' ;
         fi
       fi
+
     - >
       if [ "$TASK" = 'PHPUNIT' ];
       then
         # Create a directory for the phpunit dataroot.
         mkdir -p "$HOME"/roots/phpunit
+
         # The phpunit dataroot and prefix..
         sed -i \
           -e "/require_once/i \\\$CFG->phpunit_dataroot = '\/home\/travis\/roots\/phpunit';" \
@@ -163,6 +175,7 @@ before_script:
           -e "/require_once/i \\define('TEST_EXTERNAL_FILES_HTTP_URL', 'http://127.0.0.1:8080');" \
           -e "/require_once/i \\define('TEST_EXTERNAL_FILES_HTTPS_URL', 'http://127.0.0.1:8080');" \
           config.php ;
+
         # Redis cache store tests
         sed -i \
           -e "/require_once/i \\define('TEST_CACHESTORE_REDIS_TESTSERVERS', '127.0.0.1');" \
@@ -172,15 +185,18 @@ before_script:
         sed -i \
           -e "/require_once/i \\${redissession}" \
           config.php ;
+
         # Initialise PHPUnit for Moodle.
         php admin/tool/phpunit/cli/init.php
       fi
+
     - >
       if [ "$TASK" = 'GRUNT' ];
       then
         npm install --no-spin;
         npm install --no-spin -g grunt ;
       fi
+
     ########################################################################
     # CI Tests
     ########################################################################
@@ -189,31 +205,64 @@ before_script:
       then
         # Note - this is deliberately placed in the script section as we
         # should not add any code until after phpunit has run.
+
         # The following repositories are required.
         # The local_ci repository does the actual checking.
         git clone https://github.com/moodlehq/moodle-local_ci.git local/ci
+
         # We need the official upstream for comparison
         git remote add upstream https://github.com/moodle/moodle.git;
-        git fetch upstream master;
+
+        git fetch upstream MOODLE_310_STABLE;
         export GIT_PREVIOUS_COMMIT="`git merge-base FETCH_HEAD $TRAVIS_COMMIT`";
         export GIT_COMMIT="$TRAVIS_COMMIT";
         export UPSTREAM_FETCH_HEAD=`git rev-parse FETCH_HEAD`
+
         # Variables required by our linter.
         export gitcmd=`which git`;
         export gitdir="$TRAVIS_BUILD_DIR";
         export phpcmd=`which php`;
       fi
+
+    ########################################################################
+    # Upgrade test
+    ########################################################################
+    - >
+      if [ "$TASK" = 'UPGRADE' ];
+      then
+        # We need the official upstream.
+        git remote add upstream https://github.com/moodle/moodle.git;
+
+        # Checkout 30 STABLE branch (the first version compatible with PHP 7.x)
+        git fetch upstream MOODLE_30_STABLE;
+        git checkout MOODLE_30_STABLE;
+
+        # Perform the upgrade
+        php admin/cli/install_database.php --agree-license --adminpass=Password --adminemail=admin@example.com --fullname="Upgrade test" --shortname=Upgrade;
+
+        # Return to the previous commit
+        git checkout -;
+
+        # Perform the upgrade
+        php admin/cli/upgrade.php --non-interactive --allow-unstable ;
+
+        # The local_ci repository can be used to check upgrade savepoints.
+        git clone https://github.com/moodlehq/moodle-local_ci.git local/ci ;
+      fi
+
 script:
     - >
       if [ "$TASK" = 'PHPUNIT' ];
       then
         vendor/bin/phpunit --fail-on-risky --disallow-test-output --verbose;
       fi
+
     - >
       if [ "$TASK" = 'CITEST' ];
       then
         bash local/ci/php_lint/php_lint.sh;
       fi
+
     - >
       if [ "$TASK" = 'GRUNT' ];
       then
@@ -225,6 +274,24 @@ script:
         git reset -- npm-shrinkwrap.json ;
         git diff --cached --exit-code ;
       fi
+
+    ########################################################################
+    # Upgrade test
+    ########################################################################
+    - >
+      if [ "$TASK" = 'UPGRADE' ];
+      then
+        cp local/ci/check_upgrade_savepoints/check_upgrade_savepoints.php ./check_upgrade_savepoints.php
+        result=`php check_upgrade_savepoints.php`;
+        # Check if there are problems
+        count=`echo "$result" | grep -P "ERROR|WARN" | wc -l` ;
+        if (($count > 0));
+        then
+          echo "$result"
+          exit 1 ;
+        fi
+      fi
+
 after_script:
     - >
       if [ "$TASK" = 'PHPUNIT' ];
